# Generated by Django 5.2.7 on 2026-02-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='fecha_ultimo_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='estatus',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada')], default='Activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='forma_pago',
            field=models.CharField(choices=[('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poliza',
            name='tipo_seguro',
            field=models.CharField(choices=[('Vida', 'Vida'), ('Auto', 'Auto'), ('Gastos médicos', 'Gastos médicos')], max_length=50),
        ),
    ]
